server:
  port: 8088

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/learn?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2277906493@qq.com
    password: pwirshfkecpaecja
    from: 2277906493@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mail:
  from: ${spring.mail.username}
  to: bill_2008@hotmail.com

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.accenture.sptile.entity

#showSql
logging:
  level:
    com:
      accenture:
        sptitle:
          mapper: debug